[package]
name = "AftermathLpRule"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
BucketOracle = { git = "https://github.com/Bucket-Protocol/oracle.git", rev = "main" }
AftermathAmm = { local = "../../partners/aftermath-interfaces/packages/amm/amm" }

[addresses]
aftermath_lp_rule = "0x0"
